remote_theme: pages-themes/dinky@v0.2.0

show_downloads: false

title: Steve Simpson
description: Software and Security Engineer

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


